import Foundation

/// Central in-code localization for the reusable PDF viewer.
///
/// Translations are bundled in code so the module stays self-contained and does not depend on the
/// host application configuring `.lproj` resources. The active language is resolved from the
/// device's preferred languages, falling back to English. Clients may still override any string by
/// supplying a custom `PDFViewerStrings`.
public enum PDFViewerLocalization {

    /// Languages currently supported by the viewer.
    public static let supportedLanguageCodes = ["en", "sw", "fr", "am", "de", "es"]

    /// The active two-letter language code, resolved from the device preferences.
    public static var languageCode: String {
        for language in Locale.preferredLanguages {
            let code = String(language.prefix(2)).lowercased()
            if supportedLanguageCodes.contains(code) { return code }
        }
        return "en"
    }

    /// Returns the localized value for a key, falling back to English and then the key itself.
    public static func string(_ key: String) -> String {
        let table = translations[languageCode] ?? englishTable
        return table[key] ?? englishTable[key] ?? key
    }

    private static var englishTable: [String: String] { translations["en"] ?? [:] }

    private static let translations: [String: [String: String]] = [
        "en": [
            "back": "Back",
            "bookmarks": "Bookmarks",
            "search": "Search",
            "goToPage": "Go to Page",
            "cancel": "Cancel",
            "done": "Done",
            "page": "Page",
            "of": "of",
            "vertical": "Vertical",
            "horizontal": "Horizontal",
            "print": "Print",
            "share": "Share",
            "noBookmarks": "No Bookmarks",
            "noSearchResults": "No Results",
            "invalidPage": "Invalid page number.",
            "unableToOpenPDF": "Unable to open PDF.",
            "enterPassword": "Enter Password",
            "tableOfContents": "Table of Contents",
            "thumbnails": "Thumbnails",
            "documentInfo": "Document Info",
            "scrollDirection": "Scroll Direction",
            "displayMode": "Display Mode",
            "more": "More",
            "noOutline": "This document does not contain a table of contents.",
            "loading": "Loading\u{2026}",
            "firstPage": "First Page",
            "previousPage": "Previous Page",
            "nextPage": "Next Page",
            "lastPage": "Last Page",
            "zoomIn": "Zoom In",
            "zoomOut": "Zoom Out",
            "resetZoom": "Reset Zoom",
            "addBookmark": "Add Bookmark",
            "removeBookmark": "Remove Bookmark",
            "openDocuments": "Open Documents",
            "closeAll": "Close All",
            "close": "Close",
            "noOpenDocuments": "No Open Documents",
            "searching": "Searching\u{2026}",
            "enterKeyword": "Enter a keyword to search the document.",
            "title": "Title",
            "author": "Author",
            "subject": "Subject",
            "creator": "Creator",
            "pages": "Pages",
            "untitled": "(untitled)",
            "searchSummaryFormat": "%1$d matches on %2$d pages",
            "occurrencesFormat": "%d occurrences",
            "noMatchesForFormat": "No matches found for \"%@\"",
            "appTitle": "PDF Editor",
            "appSubtitle": "Pick any PDF from your device to open it in the viewer.",
            "appChoosePDF": "Choose PDF",
            "appNavTitle": "PDF Editor",
            "edit": "Edit",
            "save": "Save",
            "reset": "Reset",
            "editPages": "Edit Pages",
            "saveChangesTitle": "Save Changes?",
            "saveChangesMessage": "This will overwrite the current PDF with your changes.",
            "resetChangesTitle": "Reset Document?",
            "resetChangesMessage": "This will restore the original PDF with all pages.",
            "saveFailed": "Failed to save changes.",
            "resetFailed": "Failed to reset the document.",
            "minOnePage": "A document must contain at least one page."
        ],
        "sw": [
            "back": "Rudi",
            "bookmarks": "Alamisho",
            "search": "Tafuta",
            "goToPage": "Nenda kwenye Ukurasa",
            "cancel": "Ghairi",
            "done": "Imekamilika",
            "page": "Ukurasa",
            "of": "kati ya",
            "vertical": "Wima",
            "horizontal": "Mlalo",
            "print": "Chapisha",
            "share": "Shiriki",
            "noBookmarks": "Hakuna Alamisho",
            "noSearchResults": "Hakuna Matokeo",
            "invalidPage": "Nambari ya ukurasa si sahihi.",
            "unableToOpenPDF": "Imeshindwa kufungua PDF.",
            "enterPassword": "Weka Nenosiri",
            "tableOfContents": "Yaliyomo",
            "thumbnails": "Vijipicha",
            "documentInfo": "Taarifa za Hati",
            "scrollDirection": "Mwelekeo wa Kusogeza",
            "displayMode": "Hali ya Kuonyesha",
            "more": "Zaidi",
            "noOutline": "Hati hii haina yaliyomo.",
            "loading": "Inapakia\u{2026}",
            "firstPage": "Ukurasa wa Kwanza",
            "previousPage": "Ukurasa Uliopita",
            "nextPage": "Ukurasa Unaofuata",
            "lastPage": "Ukurasa wa Mwisho",
            "zoomIn": "Kuza",
            "zoomOut": "Punguza",
            "resetZoom": "Weka Upya Kuza",
            "addBookmark": "Ongeza Alamisho",
            "removeBookmark": "Ondoa Alamisho",
            "openDocuments": "Hati Zilizofunguliwa",
            "closeAll": "Funga Zote",
            "close": "Funga",
            "noOpenDocuments": "Hakuna Hati Zilizofunguliwa",
            "searching": "Inatafuta\u{2026}",
            "enterKeyword": "Weka neno kuu kutafuta hati.",
            "title": "Kichwa",
            "author": "Mwandishi",
            "subject": "Somo",
            "creator": "Muundaji",
            "pages": "Kurasa",
            "untitled": "(bila kichwa)",
            "searchSummaryFormat": "%1$d zinazolingana katika kurasa %2$d",
            "occurrencesFormat": "%d matukio",
            "noMatchesForFormat": "Hakuna zinazolingana na \"%@\"",
            "appTitle": "PDF Editor",
            "appSubtitle": "Chagua PDF yoyote kutoka kwa kifaa chako ili kuifungua.",
            "appChoosePDF": "Chagua PDF",
            "appNavTitle": "Kihariri cha PDF",
            "edit": "Hariri",
            "save": "Hifadhi",
            "reset": "Weka Upya",
            "editPages": "Hariri Kurasa",
            "saveChangesTitle": "Hifadhi Mabadiliko?",
            "saveChangesMessage": "Hii itaandika upya PDF ya sasa na mabadiliko yako.",
            "resetChangesTitle": "Weka Upya Hati?",
            "resetChangesMessage": "Hii itarejesha PDF asili na kurasa zote.",
            "saveFailed": "Imeshindwa kuhifadhi mabadiliko.",
            "resetFailed": "Imeshindwa kuweka upya hati.",
            "minOnePage": "Hati lazima iwe na angalau ukurasa mmoja."
        ],
        "fr": [
            "back": "Retour",
            "bookmarks": "Signets",
            "search": "Rechercher",
            "goToPage": "Aller à la page",
            "cancel": "Annuler",
            "done": "Terminé",
            "page": "Page",
            "of": "sur",
            "vertical": "Vertical",
            "horizontal": "Horizontal",
            "print": "Imprimer",
            "share": "Partager",
            "noBookmarks": "Aucun signet",
            "noSearchResults": "Aucun résultat",
            "invalidPage": "Numéro de page invalide.",
            "unableToOpenPDF": "Impossible d'ouvrir le PDF.",
            "enterPassword": "Saisir le mot de passe",
            "tableOfContents": "Table des matières",
            "thumbnails": "Miniatures",
            "documentInfo": "Infos du document",
            "scrollDirection": "Sens de défilement",
            "displayMode": "Mode d'affichage",
            "more": "Plus",
            "noOutline": "Ce document ne contient pas de table des matières.",
            "loading": "Chargement\u{2026}",
            "firstPage": "Première page",
            "previousPage": "Page précédente",
            "nextPage": "Page suivante",
            "lastPage": "Dernière page",
            "zoomIn": "Zoom avant",
            "zoomOut": "Zoom arrière",
            "resetZoom": "Réinitialiser le zoom",
            "addBookmark": "Ajouter un signet",
            "removeBookmark": "Supprimer le signet",
            "openDocuments": "Documents ouverts",
            "closeAll": "Tout fermer",
            "close": "Fermer",
            "noOpenDocuments": "Aucun document ouvert",
            "searching": "Recherche\u{2026}",
            "enterKeyword": "Saisissez un mot-clé pour rechercher dans le document.",
            "title": "Titre",
            "author": "Auteur",
            "subject": "Sujet",
            "creator": "Créateur",
            "pages": "Pages",
            "untitled": "(sans titre)",
            "searchSummaryFormat": "%1$d résultats sur %2$d pages",
            "occurrencesFormat": "%d occurrences",
            "noMatchesForFormat": "Aucun résultat pour « %@ »",
            "appTitle": "PDF Editor",
            "appSubtitle": "Choisissez un PDF sur votre appareil pour l'ouvrir.",
            "appChoosePDF": "Choisir un PDF",
            "appNavTitle": "Éditeur PDF",
            "edit": "Modifier",
            "save": "Enregistrer",
            "reset": "Réinitialiser",
            "editPages": "Modifier les pages",
            "saveChangesTitle": "Enregistrer les modifications ?",
            "saveChangesMessage": "Cela remplacera le PDF actuel par vos modifications.",
            "resetChangesTitle": "Réinitialiser le document ?",
            "resetChangesMessage": "Cela restaurera le PDF d'origine avec toutes les pages.",
            "saveFailed": "Échec de l'enregistrement des modifications.",
            "resetFailed": "Échec de la réinitialisation du document.",
            "minOnePage": "Un document doit contenir au moins une page."
        ],
        "am": [
            "back": "ተመለስ",
            "bookmarks": "ዕልባቶች",
            "search": "ፈልግ",
            "goToPage": "ወደ ገጽ ሂድ",
            "cancel": "ሰርዝ",
            "done": "ተከናውኗል",
            "page": "ገጽ",
            "of": "ከ",
            "vertical": "ቀጥ ያለ",
            "horizontal": "አግድም",
            "print": "አትም",
            "share": "አጋራ",
            "noBookmarks": "ምንም ዕልባቶች የሉም",
            "noSearchResults": "ውጤት የለም",
            "invalidPage": "ልክ ያልሆነ የገጽ ቁጥር።",
            "unableToOpenPDF": "ፒዲኤፍ መክፈት አልተቻለም።",
            "enterPassword": "የይለፍ ቃል አስገባ",
            "tableOfContents": "የይዘት ሠንጠረዥ",
            "thumbnails": "ድንክዬዎች",
            "documentInfo": "የሰነድ መረጃ",
            "scrollDirection": "የማሸብለል አቅጣጫ",
            "displayMode": "የማሳያ ሁኔታ",
            "more": "ተጨማሪ",
            "noOutline": "ይህ ሰነድ የይዘት ሠንጠረዥ የለውም።",
            "loading": "በመጫን ላይ\u{2026}",
            "firstPage": "የመጀመሪያ ገጽ",
            "previousPage": "ቀዳሚ ገጽ",
            "nextPage": "ቀጣይ ገጽ",
            "lastPage": "የመጨረሻ ገጽ",
            "zoomIn": "አጉላ",
            "zoomOut": "አሳንስ",
            "resetZoom": "አጉላን ዳግም አስጀምር",
            "addBookmark": "ዕልባት አክል",
            "removeBookmark": "ዕልባት አስወግድ",
            "openDocuments": "የተከፈቱ ሰነዶች",
            "closeAll": "ሁሉንም ዝጋ",
            "close": "ዝጋ",
            "noOpenDocuments": "ምንም የተከፈቱ ሰነዶች የሉም",
            "searching": "በመፈለግ ላይ\u{2026}",
            "enterKeyword": "ሰነዱን ለመፈለግ ቁልፍ ቃል ያስገቡ።",
            "title": "ርዕስ",
            "author": "ደራሲ",
            "subject": "ርዕሰ ጉዳይ",
            "creator": "ፈጣሪ",
            "pages": "ገጾች",
            "untitled": "(ርዕስ የለም)",
            "searchSummaryFormat": "%1$d ተዛማጆች በ%2$d ገጾች",
            "occurrencesFormat": "%d ክስተቶች",
            "noMatchesForFormat": "ለ\"%@\" ምንም ተዛማጅ አልተገኘም",
            "appTitle": "PDF Editor",
            "appSubtitle": "ለመክፈት ከመሣሪያዎ ማንኛውንም ፒዲኤፍ ይምረጡ።",
            "appChoosePDF": "ፒዲኤፍ ይምረጡ",
            "appNavTitle": "ፒዲኤፍ አራሚ",
            "edit": "አርትዕ",
            "save": "አስቀምጥ",
            "reset": "ዳግም አስጀምር",
            "editPages": "ገጾችን አርትዕ",
            "saveChangesTitle": "ለውጦችን ያስቀምጡ?",
            "saveChangesMessage": "ይህ የአሁኑን ፒዲኤፍ በለውጦችዎ ይተካዋል።",
            "resetChangesTitle": "ሰነዱን ዳግም ያስጀምሩ?",
            "resetChangesMessage": "ይህ ዋናውን ፒዲኤፍ ከሁሉም ገጾች ጋር ወደ ነበረበት ይመልሳል።",
            "saveFailed": "ለውጦችን ማስቀመጥ አልተሳካም።",
            "resetFailed": "ሰነዱን ዳግም ማስጀመር አልተሳካም።",
            "minOnePage": "ሰነድ ቢያንስ አንድ ገጽ ሊኖረው ይገባል።"
        ],
        "de": [
            "back": "Zurück",
            "bookmarks": "Lesezeichen",
            "search": "Suchen",
            "goToPage": "Zur Seite",
            "cancel": "Abbrechen",
            "done": "Fertig",
            "page": "Seite",
            "of": "von",
            "vertical": "Vertikal",
            "horizontal": "Horizontal",
            "print": "Drucken",
            "share": "Teilen",
            "noBookmarks": "Keine Lesezeichen",
            "noSearchResults": "Keine Ergebnisse",
            "invalidPage": "Ungültige Seitenzahl.",
            "unableToOpenPDF": "PDF kann nicht geöffnet werden.",
            "enterPassword": "Passwort eingeben",
            "tableOfContents": "Inhaltsverzeichnis",
            "thumbnails": "Miniaturansichten",
            "documentInfo": "Dokumentinfo",
            "scrollDirection": "Scrollrichtung",
            "displayMode": "Anzeigemodus",
            "more": "Mehr",
            "noOutline": "Dieses Dokument enthält kein Inhaltsverzeichnis.",
            "loading": "Wird geladen\u{2026}",
            "firstPage": "Erste Seite",
            "previousPage": "Vorherige Seite",
            "nextPage": "Nächste Seite",
            "lastPage": "Letzte Seite",
            "zoomIn": "Vergrößern",
            "zoomOut": "Verkleinern",
            "resetZoom": "Zoom zurücksetzen",
            "addBookmark": "Lesezeichen hinzufügen",
            "removeBookmark": "Lesezeichen entfernen",
            "openDocuments": "Geöffnete Dokumente",
            "closeAll": "Alle schließen",
            "close": "Schließen",
            "noOpenDocuments": "Keine geöffneten Dokumente",
            "searching": "Suche läuft\u{2026}",
            "enterKeyword": "Geben Sie ein Stichwort ein, um das Dokument zu durchsuchen.",
            "title": "Titel",
            "author": "Autor",
            "subject": "Betreff",
            "creator": "Ersteller",
            "pages": "Seiten",
            "untitled": "(ohne Titel)",
            "searchSummaryFormat": "%1$d Treffer auf %2$d Seiten",
            "occurrencesFormat": "%d Vorkommen",
            "noMatchesForFormat": "Keine Treffer für \"%@\"",
            "appTitle": "PDF Editor",
            "appSubtitle": "Wählen Sie ein beliebiges PDF auf Ihrem Gerät aus, um es zu öffnen.",
            "appChoosePDF": "PDF auswählen",
            "appNavTitle": "PDF-Editor",
            "edit": "Bearbeiten",
            "save": "Speichern",
            "reset": "Zurücksetzen",
            "editPages": "Seiten bearbeiten",
            "saveChangesTitle": "Änderungen speichern?",
            "saveChangesMessage": "Dies überschreibt das aktuelle PDF mit Ihren Änderungen.",
            "resetChangesTitle": "Dokument zurücksetzen?",
            "resetChangesMessage": "Dies stellt das ursprüngliche PDF mit allen Seiten wieder her.",
            "saveFailed": "Änderungen konnten nicht gespeichert werden.",
            "resetFailed": "Dokument konnte nicht zurückgesetzt werden.",
            "minOnePage": "Ein Dokument muss mindestens eine Seite enthalten."
        ],
        "es": [
            "back": "Atrás",
            "bookmarks": "Marcadores",
            "search": "Buscar",
            "goToPage": "Ir a la página",
            "cancel": "Cancelar",
            "done": "Listo",
            "page": "Página",
            "of": "de",
            "vertical": "Vertical",
            "horizontal": "Horizontal",
            "print": "Imprimir",
            "share": "Compartir",
            "noBookmarks": "Sin marcadores",
            "noSearchResults": "Sin resultados",
            "invalidPage": "Número de página no válido.",
            "unableToOpenPDF": "No se puede abrir el PDF.",
            "enterPassword": "Ingrese la contraseña",
            "tableOfContents": "Tabla de contenido",
            "thumbnails": "Miniaturas",
            "documentInfo": "Información del documento",
            "scrollDirection": "Dirección de desplazamiento",
            "displayMode": "Modo de visualización",
            "more": "Más",
            "noOutline": "Este documento no contiene una tabla de contenido.",
            "loading": "Cargando\u{2026}",
            "firstPage": "Primera página",
            "previousPage": "Página anterior",
            "nextPage": "Página siguiente",
            "lastPage": "Última página",
            "zoomIn": "Acercar",
            "zoomOut": "Alejar",
            "resetZoom": "Restablecer zoom",
            "addBookmark": "Añadir marcador",
            "removeBookmark": "Quitar marcador",
            "openDocuments": "Documentos abiertos",
            "closeAll": "Cerrar todo",
            "close": "Cerrar",
            "noOpenDocuments": "No hay documentos abiertos",
            "searching": "Buscando\u{2026}",
            "enterKeyword": "Introduzca una palabra clave para buscar en el documento.",
            "title": "Título",
            "author": "Autor",
            "subject": "Asunto",
            "creator": "Creador",
            "pages": "Páginas",
            "untitled": "(sin título)",
            "searchSummaryFormat": "%1$d coincidencias en %2$d páginas",
            "occurrencesFormat": "%d apariciones",
            "noMatchesForFormat": "No se encontraron coincidencias para \"%@\"",
            "appTitle": "PDF Editor",
            "appSubtitle": "Elige cualquier PDF de tu dispositivo para abrirlo.",
            "appChoosePDF": "Elegir PDF",
            "appNavTitle": "Editor PDF",
            "edit": "Editar",
            "save": "Guardar",
            "reset": "Restablecer",
            "editPages": "Editar páginas",
            "saveChangesTitle": "¿Guardar cambios?",
            "saveChangesMessage": "Esto sobrescribirá el PDF actual con tus cambios.",
            "resetChangesTitle": "¿Restablecer documento?",
            "resetChangesMessage": "Esto restaurará el PDF original con todas las páginas.",
            "saveFailed": "No se pudieron guardar los cambios.",
            "resetFailed": "No se pudo restablecer el documento.",
            "minOnePage": "Un documento debe contener al menos una página."
        ]
    ]
}
